<a href="https://colab.research.google.com/github/drpetros11111/Tensorflow_Portilia/blob/Dataframe/04_Groupby.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Groupby

The groupby method allows you to group rows of data together and call aggregate functions

In [1]:
import pandas as pd

In [2]:
# We will cover reading in data in a lot more detail in a later lecture!
df = pd.read_csv('/content/Universities.csv')

In [3]:
# Show first N rows (N=5 by default)
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

Now you can use the .groupby() method to group rows together based off of a **categorical** column. This column will then be reassigned to be the index.

Notice we have 2 steps:

1. Choose a categorical column to group by
2. Choose your aggregation function. Recall an aggregation function should take multiple values and return a single value (e.g. max,min, mean, std, etc...)

In [4]:
# Step 1 simply returns a special groupby object waiting to have an aggregate method called on it!
df.groupby('Year')

In [9]:
# Calculate the mean of numeric columns only and round the result
df.groupby('Year').mean(numeric_only=True).round(2)

      Completions
Year
2012       535.08
2013       526.15
2014       588.81
2015       597.25
2016       609.86

In [12]:
type(df.groupby('Year').mean(numeric_only=True))

pandas.core.frame.DataFrame

In [14]:
df.groupby('Year').mean(numeric_only = True).round(2).sort_index(ascending=False)

      Completions
Year
2016       609.86
2015       597.25
2014       588.81
2013       526.15
2012       535.08

In [15]:
df.groupby('Year').count()

      Sector  University  Completions  Geography
Year
2012      38          38           38         38
2013      40          40           40         40
2014      42          42           42         42
2015      44          44           44         44
2016      43          43           43         43

In [19]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

In [22]:
# Perform a groupby on multiple columns
df.groupby(['Year', 'University', 'Geography', 'Sector']).sum()

Completions    5388
dtype: int64

In [23]:
import pandas as pd

# Assuming df is already defined as the DataFrame

# Perform a groupby on multiple columns and sum the 'Completions' column
df_grouped = df.groupby(['Year', 'University', 'Geography', 'Sector'], as_index=False).sum()

# Print the resulting DataFrame with all columns and their values
print(df_grouped)

     Year                             University Geography  \
0    2012       Academy of Hair Design-Las Vegas    Nevada
1    2012            Advanced Training Institute    Nevada
2    2012           Brightwood College-Las Vegas    Nevada
3    2012      Career College of Northern Nevada    Nevada
4    2012           Carrington College-Las Vegas    Nevada
..    ...                                    ...       ...
202  2016              University of Nevada-Reno    Nevada
203  2016           University of Phoenix-Nevada    Nevada
204  2016  Utah College of Massage Therapy-Vegas    Nevada
205  2016                 Western Nevada College    Nevada
206  2016  Wongu University of Oriental Medicine    Nevada

                                      Sector  Completions
0       Private for-profit, less-than 2-year          110
1       Private for-profit, less-than 2-year          218
2                 Private for-profit, 2-year          568
3                 Private for-profit, 2-year          333
4                 Private for-profit, 2-year          120
..                                       ...          ...
202                  Public, 4-year or above         4309
203      Private for-profit, 4-year or above          423
204     Private for-profit, less-than 2-year          240
205                  Public, 4-year or above          960
206  Private not-for-profit, 4-year or above            0

[207 rows x 5 columns]

In [24]:
import pandas as pd

# Assuming df is already defined as the DataFrame

# Perform a groupby on multiple columns and sum the 'Completions' column
df_grouped = df.groupby(['Year', 'University', 'Geography', 'Sector'], as_index=False).sum().max()

# Print the resulting DataFrame with all columns and their values
print(df_grouped)

Year                                            2016
University     Wongu University of Oriental Medicine
Geography                                     Nevada
Sector                       Public, 4-year or above
Completions                                     5388
dtype: object

In [25]:
import pandas as pd

# Assuming df is already defined as the DataFrame

# Perform a groupby on multiple columns and sum the 'Completions' column
df_grouped = df.groupby(['Year', 'University', 'Geography', 'Sector'], as_index=False).sum().std()

# Print the resulting DataFrame with all columns and their values
print(df_grouped)

TypeError: could not convert string to float: 'Academy of Hair Design-Las Vegas'

In [28]:
import pandas as pd

# Assuming df is already defined as the DataFrame

# Perform a groupby on multiple columns and sum the 'Completions' column
df_grouped = df.groupby(['Year', 'University', 'Geography', 'Sector'], as_index=False)['Completions'].sum() # Only include the 'Completions' column in the aggregation

# Calculate the standard deviation of the 'Completions' column
df_std = df_grouped['Completions'].std()
# Print the resulting standard deviation
print(f'the standard deviation is : {df_std}')

the standard deviation is : 1125.247728916997

In [30]:
import pandas as pd

# Assuming df is already defined as the DataFrame

# Perform a groupby on multiple columns and sum the 'Completions' column
df_grouped = df.groupby(['Year', 'University', 'Geography', 'Sector'], as_index=False)['Completions'].sum() # Only include the 'Completions' column in the aggregation

# Calculate the standard deviation of the 'Completions' column
df_std = df_grouped['Completions'].std()
# Print the resulting standard deviation
print(f'The standard deviation is: {round(df_std, 2)}')
# Example value, replace with your actual std value
print(f'The standard deviation is: {df_std:,.2f}')

The standard deviation is: 1125.25
The standard deviation is: 1,125.25

-----
## Other Aggregate Functions

<table><td><tt
><span
>count</span></tt></td><td>Number of non-null observations</td></tr><tr
><td><tt
><span
>sum</span></tt></td><td>Sum of values</td></tr><tr
><td><tt
><span
>mean</span></tt></td><td>Mean of values</td></tr><tr
><td><tt
><span
>mad</span></tt></td><td>Mean absolute deviation</td></tr><tr
><td><tt
><span
>median</span></tt></td><td>Arithmetic median of values</td></tr><tr
><td><tt
><span
>min</span></tt></td><td>Minimum</td></tr><tr
><td><tt
><span
>max</span></tt></td><td>Maximum</td></tr><tr
><td><tt
><span
>mode</span></tt></td><td>Mode</td></tr><tr
><td><tt
><span
>abs</span></tt></td><td>Absolute Value</td></tr><tr
><td><tt
><span
>prod</span></tt></td><td>Product of values</td></tr><tr
><td><tt
><span
>std</span></tt></td><td>Unbiased standard deviation</td></tr><tr
><td><tt
><span
>var</span></tt></td><td>Unbiased variance</td></tr><tr
><td><tt
><span
>sem</span></tt></td><td>Unbiased standard error of the mean</td></tr><tr
><td><tt
><span
>skew</span></tt></td><td>Unbiased skewness (3rd moment)</td></tr><tr
><td><tt
><span
>kurt</span></tt></td><td>Unbiased kurtosis (4th moment)</td></tr><tr
><td><tt
><span
>quantile</span></tt></td><td>Sample quantile (value at %)</td></tr><tr
><td><tt
><span
>cumsum</span></tt></td><td>Cumulative sum</td></tr><tr
><td><tt
><span
>cumprod</span></tt></td><td>Cumulative product</td></tr><tr
><td><tt
><span
>cummax</span></tt></td><td>Cumulative maximum</td></tr><tr
><td><tt
><span
>cummin</span></tt></td><td>Cumulative minimum</td></tr></tbody></table>

----

## Grouping By multiple columns

In [31]:
df.head()

,Sector,University,Year,Completions,Geography
0,"Private for-profit, 2-year",Pima Medical Institute-Las Vegas,2016,591,Nevada
1,"Private for-profit, less-than 2-year",Healthcare Preparatory Institute,2016,28,Nevada
2,"Private for-profit, less-than 2-year",Milan Institute-Las Vegas,2016,408,Nevada
3,"Private for-profit, less-than 2-year",Utah College of Massage Therapy-Vegas,2016,240,Nevada
4,"Public, 4-year or above",Western Nevada College,2016,960,Nevada

In [38]:
import pandas as pd

# Sample data
data = {'Sector': ['Private for-profit, 2-year', 'Private for-profit, less-than 2-year',
                   'Private for-profit, less-than 2-year', 'Private for-profit, less-than 2-year',
                   'Public, 4-year or above'],
        'University': ['Pima Medical Institute-Las Vegas', 'Healthcare Preparatory Institute',
                       'Milan Institute-Las Vegas', 'Utah College of Massage Therapy-Vegas',
                       'Western Nevada College'],
        'Year': [2016, 2016, 2016, 2016, 2016],
        'Completions': [591, 28, 408, 240, 960],
        'Geography': ['Nevada', 'Nevada', 'Nevada', 'Nevada', 'Nevada']}

df = pd.DataFrame(data)

# Grouping by 'Year' and 'Sector' and calculating the mean of 'Completions' only
df_grouped = df.groupby(['Year', 'Sector'])['Completions'].mean().round(2) #Removed round() from the groupby object and called it on the result of the mean aggregation.

# Print the result
print(df_grouped)

Year  Sector
2016  Private for-profit, 2-year              591.00
      Private for-profit, less-than 2-year    225.33
      Public, 4-year or above                 960.00
Name: Completions, dtype: float64

# Groupby along with other aggregate functions
This code snippet demonstrates how to create and manipulate a DataFrame in Pandas to perform a groupby operation and calculate the mean of a specific column.

----------------------

# 1. Import Pandas Library:

    import pandas as pd
Imports the Pandas library, which is essential for data manipulation and analysis.

----------------------
#2. Create Sample Data:

    data = {'Sector': ['Private for-profit, 2-year', 'Private for-profit, less-than 2-year',
                   'Private for-profit, less-than 2-year', 'Private for-profit, less-than 2-year',
                   'Public, 4-year or above'],
        'University': ['Pima Medical Institute-Las Vegas', 'Healthcare Preparatory Institute',
                       'Milan Institute-Las Vegas', 'Utah College of Massage Therapy-Vegas',
                       'Western Nevada College'],
        'Year': [2016, 2016, 2016, 2016, 2016],
        'Completions': [591, 28, 408, 240, 960],
        'Geography': ['Nevada', 'Nevada', 'Nevada', 'Nevada', 'Nevada']}

Creates a dictionary data with columns: 'Sector', 'University', 'Year', 'Completions', and 'Geography'.

Each key in the dictionary represents a column name, and the associated list contains the column values.

-----------------------------------
#3. Convert Dictionary to DataFrame:

    df = pd.DataFrame(data)

Converts the dictionary data into a Pandas DataFrame df.

The DataFrame is a tabular data structure where rows and columns are indexed, allowing for efficient data manipulation.

-------------------
#4. Group Data and Calculate Mean:

    df_grouped = df.groupby(['Year', 'Sector'])['Completions'].mean()

df.groupby(['Year', 'Sector']):

Groups the DataFrame by the 'Year' and 'Sector' columns.

Each unique combination of these columns creates a group.

['Completions']:

Selects the 'Completions' column to perform the aggregation.

.mean():

Calculates the mean of the 'Completions' column for each group.

----------------------------
#5. Print the Result:

    print(df_grouped)
Displays the resulting Series df_grouped where the index is the unique combinations of 'Year' and 'Sector', and the values are the mean completions for each group.

-------------------------
##Example Output:

Year  Sector                               
2016  Private for-profit, 2-year                 591.000000
      Private for-profit, less-than 2-year       225.333333
      Public, 4-year or above                    960.000000

Name: Completions, dtype: float64

Year and Sector are the index levels in the output.

Mean of Completions: Shows the average number of completions for each unique combination of Year and Sector.

----------------------------------
#Summary
The code creates a DataFrame from sample data, groups the data by Year and Sector, calculates the mean value of the Completions column for each group, and prints the results. This demonstrates a common data aggregation task in Pandas.

In [ ]:
df.groupby('Year').describe()

     Completions
           count        mean          std   min     25%    50%     75%     max
Year
2012        38.0  535.078947  1036.433239  13.0  114.25  229.5  420.50  5388.0
2013        40.0  526.150000  1040.474782   0.0   98.50  189.0  413.00  5278.0
2014        42.0  588.809524  1150.355857   0.0  104.50  203.5  371.75  5093.0
2015        44.0  597.250000  1183.371791   0.0   87.75  191.0  405.75  5335.0
2016        43.0  609.860465  1235.952796   0.0   90.00  208.0  414.00  5367.0

In [ ]:
df.groupby('Year').describe().transpose()

Year                      2012         2013         2014         2015  \
Completions count    38.000000    40.000000    42.000000    44.000000
            mean    535.078947   526.150000   588.809524   597.250000
            std    1036.433239  1040.474782  1150.355857  1183.371791
            min      13.000000     0.000000     0.000000     0.000000
            25%     114.250000    98.500000   104.500000    87.750000
            50%     229.500000   189.000000   203.500000   191.000000
            75%     420.500000   413.000000   371.750000   405.750000
            max    5388.000000  5278.000000  5093.000000  5335.000000

Year                      2016
Completions count    43.000000
            mean    609.860465
            std    1235.952796
            min       0.000000
            25%      90.000000
            50%     208.000000
            75%     414.000000
            max    5367.000000

# Great Job!